// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLResource" GDExtension class.</summary>
public partial class FSLResource
{
    public static readonly StringName GDClassName = "FSLResource";

    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>
    public RefCounted Inner { get; }

    public FSLResource(GodotObject inner)
    {
        Inner = (RefCounted)inner;
    }

    public static implicit operator Variant(FSLResource wrapper) => wrapper?.Inner ?? default;

    /// <summary>Wraps a GDExtension object in the most-derived C# wrapper for its Godot class.</summary>
    public static FSLResource Wrap(GodotObject inner) => inner?.GetClass() switch
    {
        null => null,
        "FSLRawResource" => new FSLRawResource(inner),
        "FSLStorageBuffer" => new FSLStorageBuffer(inner),
        "FSLUniformBuffer" => new FSLUniformBuffer(inner),
        "FSLVertexBuffer" => new FSLVertexBuffer(inner),
        "FSLIndexBuffer" => new FSLIndexBuffer(inner),
        "FSLTexture2D" => new FSLTexture2D(inner),
        "FSLTexture2DArray" => new FSLTexture2DArray(inner),
        "FSLTextureView" => new FSLTextureView(inner),
        _ => new FSLResource(inner),
    };

    public Rid GetRid() => Inner.Call(MethodName.GetRid).As<Rid>();

    public void ConnectAndCall(Callable eventHandler) => Inner.Call(MethodName.ConnectAndCall, eventHandler);

    public static class MethodName
    {
        public static readonly StringName GetRid = "get_rid";
        public static readonly StringName ConnectAndCall = "connect_and_call";
    }

    public static class SignalName
    {
        public static readonly StringName RidChanged = "rid_changed";
    }
}
