// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLTextureView" GDExtension class.</summary>
public partial class FSLTextureView : FSLTexture
{
    public new static readonly StringName GDClassName = "FSLTextureView";

    public FSLTextureView(GodotObject inner) : base(inner) { }

    public FSLTextureView() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }
}
