// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLUniformBuffer" GDExtension class.</summary>
public partial class FSLUniformBuffer : FSLBuffer
{
    public new static readonly StringName GDClassName = "FSLUniformBuffer";

    public FSLUniformBuffer(GodotObject inner) : base(inner) { }

    public FSLUniformBuffer() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public void SetField(StringName field, Variant value) => Inner.Call(MethodName.SetField, field, value);

    public void SetBuffer(Godot.Collections.Dictionary<StringName, Variant> values) => Inner.Call(MethodName.SetBuffer, values);

    public new static class MethodName
    {
        public static readonly StringName SetField = "set_field";
        public static readonly StringName SetBuffer = "set_buffer";
    }
}
