<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="assets\.DS_Store" />
    <Content Include="assets\Shaders\Compute\FSL\fft_optim.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\old\fft.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\old\tessendorf_funcs.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\shared_resources.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\spectrums.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\spreadings.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\sum_of_sines\sum_of_sines.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\temp.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\tess_funcs_optim.fsl" />
    <Content Include="assets\Textures\Epic_BlueSunset_EquiRect_flat.png" />
    <Content Include="assets\Textures\Epic_BlueSunset_EquiRect_flat.png.import" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scenes\" />
  </ItemGroup>
</Project>