// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLTexture2D" GDExtension class.</summary>
public partial class FSLTexture2D : FSLTexture
{
    public new static readonly StringName GDClassName = "FSLTexture2D";

    public FSLTexture2D(GodotObject inner) : base(inner) { }

    public FSLTexture2D() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public void SetTexture(uint texWidth, uint texHeight, Image image = null) => Inner.Call(MethodName.SetTexture, texWidth, texHeight, image);

    public new static class MethodName
    {
        public static readonly StringName SetTexture = "set_texture";
    }
}
